site_name: Version Control User Documentation
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys

repo_url: https://github.com/BCOMM-User-Documentation/Github-User-Documentation
repo_name: Version-Control-Documentation

nav:
  - Introduction: 'index.md'
  - Instructions:
    - Task 1 - Creating a Local Repository: 'localRepo.md'
    - Task 2 - Creating and Merging a Branch: 'branching.md'
    - Task 3 - Creating a Remote Repository: 'remote.md'
  - Glossary: 'glossary.md'
  - Troubleshooting: 'trouble.md'

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
  nav_style: dark
  features:
    - content.code.copy
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
  markdown_extensions:
    - attr_list
